### PR TITLE
Application Skeleton

### PR DESCRIPTION
**Pull request by ghost**
This is the initial skeleton/plumbing of the application.

### CODE REVIEW

**Comment by ChaudhryAbdullah** [comment]
When will we start work time?

Sent from my Windows Phone

**Comment by ChaudhryAbdullah** [comment]
When will we start work?

Sent from my Windows Phone

**Comment by ghost** [comment]
give me 20 mins ..

Date: Wed, 15 Apr 2015 08:39:58 -0700

**Comment by ChaudhryAbdullah** [comment]
I will be free in one hour

Sent from my Windows Phone

**Comment by ghost** [comment]
ok

Date: Wed, 15 Apr 2015 09:52:50 -0700

**Pull request merged**
